version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: casa-benetti-db
    environment:
      POSTGRES_DB: casa_benetti
      POSTGRES_USER: wtcdb
      POSTGRES_PASSWORD: Guao2023
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
