name: CI

on:
  push:
    branches:
      - pre-main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Api premain
        if: github.ref == 'refs/heads/pre-main'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER}}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/casa-benetti/api
            git checkout pre-main
            git pull
            cd /home/ubuntu/casa-benetti
            docker compose up -d --build api
